-- Local/non-production rollback companion. This destroys all private-housewarming data.
drop table if exists public.sensitive_action_audit;
drop table if exists public.plus_one_requests;
drop table if exists public.event_memberships;
drop table if exists public.invitations;
drop table if exists public.event_sensitive_details;
drop table if exists public.events;
drop table if exists public.trusted_connections;
drop table if exists public.profiles;
drop function if exists public.decide_plus_one(uuid, boolean);
drop function if exists public.propose_plus_one(uuid, uuid, text, text);
drop function if exists public.revoke_invitation(uuid);
drop function if exists public.approve_membership(uuid, boolean);
drop function if exists public.respond_to_invitation(uuid, boolean);
drop function if exists public.create_private_invitation(uuid, uuid, timestamptz);
drop function if exists public.create_private_event(text, text, date, time, time, text, text, integer, public.plus_one_policy, boolean, boolean, text, text, text);
drop function if exists public.can_view_profile(uuid);
drop function if exists public.has_approved_membership(uuid, uuid);
drop function if exists public.has_event_membership(uuid, uuid);
drop function if exists public.is_event_host(uuid);
drop function if exists public.handle_new_user();
drop function if exists public.prevent_profile_privilege_escalation();
drop function if exists public.set_updated_at();
drop type if exists public.plus_one_request_status;
drop type if exists public.connection_status;
drop type if exists public.rsvp_status;
drop type if exists public.membership_approval_status;
drop type if exists public.membership_role;
drop type if exists public.invitation_status;
drop type if exists public.plus_one_policy;
drop type if exists public.event_status;
